server:
    port: 8769
spring: 
    application:
      name: zipkin-server
eureka: 
   client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/ #注册服务器地址
management: 
   security:
    enabled: false #关闭验证


